### ISSUE TITLE
Why archive and remove the output files?

### ISSUE THREAD

**Issue by pmhausen** [ysde/grafana-backup-tool#51]
Hi!

This is a nice tool and I really appreciate your work. I changed (quick and dirty) the bash script to simply not remove the files and changed the output directory from "_OUTPUT_" to "backup".
Similarly I removed the timestamp from the dashboards.txt file.

After a run of the script I add, commit, push ... why versioned tar archives and filenames when there's git?

Kind regards,
Patrick

**Comment by ysde** [comment]
Hi @pmhausen  

Thank you.

The first thought is setting a cronjob or timer to trigger the backup program, and it will back up to the same folder, and keeping versioned files is because in case we do something wrong but backed up files were overwritten.

Any improvements of this project are welcome.

Thank you

**Comment by acjohnson** [comment]
@pmhausen The tool now supports the `--no-archive` flag does this help you?

**Comment by ysde** [comment]
Hi @pmhausen 

I'll close this first, if there is further issuers, please post again.

Many thanks
