### ISSUE TITLE
Key Error in api_checks.py

### ISSUE THREAD

**Issue by jdmaloney** [ysde/grafana-backup-tool#94]
OS: CentOS Linux release 8.2.2004
Grafana Version: 7.1.5

I'm getting the following Key Error whenever I'm attempting to run the backup of Grafana:
```
[root@grafana-test backup]# ./backup_grafana.sh /root/grafana-tools/backup/grafana_backup/conf/grafanaSettings.json
grafana health: http://localhost:3000/api/health
[DEBUG] resp status: 200
[DEBUG] resp body: {'database': 'ok'}
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/grafana-tools/backup/grafana_backup/cli.py", line 54, in <module>
    main()
  File "/root/grafana-tools/backup/grafana_backup/cli.py", line 43, in main
    save(args, settings)
  File "/root/grafana-tools/backup/grafana_backup/save.py", line 24, in main
    (status, json_resp, api_version) = api_checks(settings)
  File "/root/grafana-tools/backup/grafana_backup/api_checks.py", line 16, in main
    api_version = json_resp['version']
KeyError: 'version'
```

I've tried installing both via pypi and via the repo with the same result.  From debug output it looks like it's connecting to the local running Grafana instance fine with the api key.

**Comment by acjohnson** [comment]
I am unable to reproduce. Please follow these steps (I'm using Ubuntu 20.04) and let me know if you get a different result

```
# git clone https://github.com/ysde/grafana-backup-tool.git
# virtualenv -p $(which python3.8) venv
# source venv/bin/activate
# pip install .

# docker run -d --name=grafana -p 3000:3000 grafana/grafana
```
Browse to http://localhost:3000, login, create Admin backup API Key

Create grafanaBackup.json replacing xxxx with the key generated above
```
# cat << EOF > ./grafanaSettings.json
{
  "general": {
    "debug": true,
    "verify_ssl": false,
    "backup_dir": "_OUTPUT_",
    "pretty_print": true
  },
  "grafana": {
    "url": "http://localhost:3000",
    "token": "xxxx",
    "search_api_limit": 5000
  }
}
EOF

```
Backups run

```
# ./backup_grafana.sh grafanaSettings.json 
grafana health: http://localhost:3000/api/health
[DEBUG] resp status: 200
[DEBUG] resp body: {'commit': '8101355285', 'database': 'ok', 'version': '7.1.0'}
grafana auth check: http://localhost:3000/api/auth/keys
[DEBUG] resp status: 200
[DEBUG] resp body: [{'id': 1, 'name': 'backup', 'role': 'Admin'}]

########################################

search dashboard in grafana: http://localhost:3000/api/search/?type=dash-db&limit=5000&page=1
[DEBUG] resp status: 200
[DEBUG] resp body: []
There are 0 dashboards:

########################################

search datasources in grafana:
[DEBUG] resp status: 200
[DEBUG] resp body: []
There are 0 datasources:

########################################

search folder in grafana:
[DEBUG] resp status: 200
[DEBUG] resp body: []
There are 0 folders:

########################################


########################################

search alert channels in grafana: http://localhost:3000/api/alert-notifications
[DEBUG] resp status: 200
[DEBUG] resp body: []
There are 0 channels:

########################################

[ERROR] Backing up organizations needs to set GRAFANA_ADMIN_ACCOUNT and GRAFANA_ADMIN_PASSWORD first.

########################################

[ERROR] Backing up users needs to set ENV GRAFANA_ADMIN_ACCOUNT and GRAFANA_ADMIN_PASSWORD first. 


########################################

backup folders at: _OUTPUT_/folders/202009251020
backup datasources at: _OUTPUT_/datasources/202009251020
backup dashboards at: _OUTPUT_/dashboards/202009251020
backup alert_channels at: _OUTPUT_/alert_channels/202009251020

created archive at: _OUTPUT_/202009251020.tar.gz
```

**Comment by acjohnson** [comment]
@jdmaloney another option would be to add a `print(str(json_resp))` in `api_checks.py` so we can see what is being returned by your grafana installation

**Comment by bzed** [comment]
My grafana returns
```
{
  "database": "ok"
}
```

so that will obviously fail.

**Comment by bzed** [comment]
Reason for that is this config setting:

```
# mask the Grafana version number for unauthenticated users
hide_version = true

```

If hide_version is ``false``, the version is shown in the health info.

**Comment by acjohnson** [comment]
ah I see, are there privacy reasons for needing to set `hide_version` to true? This tool has various code paths based on the grafana version so it'd need a config option to manually set the grafana version in order to maintain compatibility with setting `hide_version` to true.

If you are willing/able to at least temporarily set `hide_version` to false during the backup/restore operation that could be a work around in your case.

**Comment by Mikey1993** [comment]
@acjohnson @ysde , Looks like it would be beneficial for the code to detect if the Grafana version it's trying to backup has the search limit or not before deciding on the way of dispatching the API calls instead of just trying to figure out the exact version from the response of the API.

<h2>Some history:</h2>
The reason there is a detection of the version was because the API changed from Grafana v6.2+ to have the limit of 5000 results per API call.

They basically added the `page` variable ([here](https://grafana.com/docs/grafana/v6.2/http_api/folder_dashboard_search/)) to be able to fetch all the data, but now with more than one request.
Also, look at issue #32.

**Comment by acjohnson** [comment]
@Mikey1993 another reason to detect Grafana version is due to API changes that affect the dashboard backup process. Grafana version 5.0.0 and newer added unique uid's for dashboards to allow for multiple dashboards with the same name

https://github.com/ysde/grafana-backup-tool/pull/112/files#diff-61a1f977d7fc7eb7521198bb0b07e48823f7d24d111a1ca6de3364bbf9a72b97R60

A try/except could be implemented to do away with the Grafana version detection for this as well though I think.

**Comment by acjohnson** [comment]
@bzed can you confirm this is solved?

**Comment by bzed** [comment]
> @bzed can you confirm this is solved?

yes, works perfectly fine. Thank you!
